### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by silentrob** [xissy/node-stanford-simple-nlp#4]
1. Readme 
   
   var options = {
       annotators: ['tokenize', 'ssplit', 'pos', 'lemma', 'ner', 'parse' 'dcoref']
   };

Should be 

```
var options = {
  annotators: ['tokenize', 'ssplit', 'pos', 'lemma', 'ner', 'parse', 'dcoref']
};
```
1. jar folder should say to move the JAR files in, not just unzip the archive into the jar folder.

**Comment by TuningGuide** [comment]
This somehow did not made it into the readme of master branch.
