### ISSUE TITLE
loadPipeline Initialization

### ISSUE THREAD

**Issue by latkinso42** [xissy/node-stanford-simple-nlp#6]
I see  there has been a recent change in the description of Async vs Sync. This is a great step foreword. 

However, for me, The code example for the Async mode still reports 'Load a pipeline first'. Also the Warning has an effective double negative "didn't" and "without" which is  a bit confusing with respect to both examples..

Respectfully...

**Comment by Izhaki** [comment]
Same issue as @hypersundays, any idea how to fix this?
